name: Clear Cache

on:
  schedule:
    - cron: "50 1 * * *" # Daily before scheduled CI cache warmup
  workflow_dispatch:

jobs:
  clear:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Clear all caches
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh cache delete --all --repo ${{ github.repository }}
